
// This file has been generated by the GUI designer. Do not modify.
namespace Burner
{
	public partial class MainWindow
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Button btnDown;
		
		private global::Gtk.Button btnLeft;
		
		private global::Gtk.Button btnRight;
		
		private global::Gtk.Button btnStop;
		
		private global::Gtk.Button btnUnknown;
		
		private global::Gtk.Button btnUp;
		
		private global::Gtk.HScrollbar sclPower;
		
		private global::Gtk.Button btnHalt;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label lblPower;
		
		private global::Gtk.HScale sclBitmapPower;
		
		private global::Gtk.Label lblLinger;
		
		private global::Gtk.HScale sclLinger;
		
		private global::Gtk.Label lblSpeed;
		
		private global::Gtk.HScale sclSpeed;
		
		private global::Gtk.Label lblStepSize;
		
		private global::Gtk.HScale sclStepSize;
		
		private global::Gtk.Label lbWT;
		
		private global::Gtk.HScale sclWT;
		
		private global::Gtk.Button btnBurn;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.FileChooserButton fileImage;
		
		private global::Gtk.Image imgPreview;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView txtLog;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Burner.MainWindow
			this.Events = ((global::Gdk.EventMask)(3072));
			this.Name = "Burner.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(3));
			// Container child Burner.MainWindow.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.btnDown = new global::Gtk.Button ();
			this.btnDown.CanFocus = true;
			this.btnDown.Name = "btnDown";
			this.btnDown.UseUnderline = true;
			this.btnDown.Label = global::Mono.Unix.Catalog.GetString ("v");
			this.table1.Add (this.btnDown);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnDown]));
			w1.TopAttach = ((uint)(2));
			w1.BottomAttach = ((uint)(3));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnLeft = new global::Gtk.Button ();
			this.btnLeft.CanFocus = true;
			this.btnLeft.Name = "btnLeft";
			this.btnLeft.UseUnderline = true;
			this.btnLeft.Label = global::Mono.Unix.Catalog.GetString ("<");
			this.table1.Add (this.btnLeft);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnLeft]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnRight = new global::Gtk.Button ();
			this.btnRight.CanFocus = true;
			this.btnRight.Name = "btnRight";
			this.btnRight.UseUnderline = true;
			this.btnRight.Label = global::Mono.Unix.Catalog.GetString (">");
			this.table1.Add (this.btnRight);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnRight]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnStop = new global::Gtk.Button ();
			this.btnStop.CanFocus = true;
			this.btnStop.Name = "btnStop";
			this.btnStop.UseUnderline = true;
			this.btnStop.Label = global::Mono.Unix.Catalog.GetString ("Stop");
			this.table1.Add (this.btnStop);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnStop]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnUnknown = new global::Gtk.Button ();
			this.btnUnknown.CanFocus = true;
			this.btnUnknown.Name = "btnUnknown";
			this.btnUnknown.UseUnderline = true;
			this.btnUnknown.Label = global::Mono.Unix.Catalog.GetString ("?");
			this.table1.Add (this.btnUnknown);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnUnknown]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnUp = new global::Gtk.Button ();
			this.btnUp.CanFocus = true;
			this.btnUp.Events = ((global::Gdk.EventMask)(768));
			this.btnUp.Name = "btnUp";
			this.btnUp.UseUnderline = true;
			this.btnUp.Label = global::Mono.Unix.Catalog.GetString ("^");
			this.table1.Add (this.btnUp);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnUp]));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.sclPower = new global::Gtk.HScrollbar (null);
			this.sclPower.Name = "sclPower";
			this.sclPower.Adjustment.Upper = 255;
			this.sclPower.Adjustment.PageIncrement = 10;
			this.sclPower.Adjustment.PageSize = 10;
			this.sclPower.Adjustment.StepIncrement = 1;
			this.vbox1.Add (this.sclPower);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.sclPower]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.btnHalt = new global::Gtk.Button ();
			this.btnHalt.CanFocus = true;
			this.btnHalt.Name = "btnHalt";
			this.btnHalt.UseUnderline = true;
			this.btnHalt.Label = global::Mono.Unix.Catalog.GetString ("Halt");
			this.vbox1.Add (this.btnHalt);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.btnHalt]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.hbox1.Add (this.vbox1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblPower = new global::Gtk.Label ();
			this.lblPower.Name = "lblPower";
			this.lblPower.LabelProp = global::Mono.Unix.Catalog.GetString ("Power");
			this.vbox2.Add (this.lblPower);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblPower]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.sclBitmapPower = new global::Gtk.HScale (null);
			this.sclBitmapPower.CanFocus = true;
			this.sclBitmapPower.Name = "sclBitmapPower";
			this.sclBitmapPower.Inverted = true;
			this.sclBitmapPower.Adjustment.Upper = 255;
			this.sclBitmapPower.Adjustment.PageIncrement = 10;
			this.sclBitmapPower.Adjustment.StepIncrement = 1;
			this.sclBitmapPower.Adjustment.Value = 250;
			this.sclBitmapPower.DrawValue = true;
			this.sclBitmapPower.Digits = 0;
			this.sclBitmapPower.ValuePos = ((global::Gtk.PositionType)(2));
			this.vbox2.Add (this.sclBitmapPower);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.sclBitmapPower]));
			w12.Position = 1;
			w12.Expand = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblLinger = new global::Gtk.Label ();
			this.lblLinger.Name = "lblLinger";
			this.lblLinger.LabelProp = global::Mono.Unix.Catalog.GetString ("Linger time");
			this.vbox2.Add (this.lblLinger);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblLinger]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.sclLinger = new global::Gtk.HScale (null);
			this.sclLinger.CanFocus = true;
			this.sclLinger.Name = "sclLinger";
			this.sclLinger.Adjustment.Upper = 1000;
			this.sclLinger.Adjustment.PageIncrement = 10;
			this.sclLinger.Adjustment.StepIncrement = 5;
			this.sclLinger.Adjustment.Value = 250;
			this.sclLinger.DrawValue = true;
			this.sclLinger.Digits = 0;
			this.sclLinger.ValuePos = ((global::Gtk.PositionType)(2));
			this.vbox2.Add (this.sclLinger);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.sclLinger]));
			w14.Position = 3;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblSpeed = new global::Gtk.Label ();
			this.lblSpeed.Name = "lblSpeed";
			this.lblSpeed.LabelProp = global::Mono.Unix.Catalog.GetString ("Speed");
			this.vbox2.Add (this.lblSpeed);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblSpeed]));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.sclSpeed = new global::Gtk.HScale (null);
			this.sclSpeed.CanFocus = true;
			this.sclSpeed.Name = "sclSpeed";
			this.sclSpeed.Inverted = true;
			this.sclSpeed.Adjustment.Lower = 1;
			this.sclSpeed.Adjustment.Upper = 12;
			this.sclSpeed.Adjustment.PageIncrement = 3;
			this.sclSpeed.Adjustment.StepIncrement = 1;
			this.sclSpeed.Adjustment.Value = 6;
			this.sclSpeed.DrawValue = true;
			this.sclSpeed.Digits = 0;
			this.sclSpeed.ValuePos = ((global::Gtk.PositionType)(2));
			this.vbox2.Add (this.sclSpeed);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.sclSpeed]));
			w16.Position = 5;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblStepSize = new global::Gtk.Label ();
			this.lblStepSize.Name = "lblStepSize";
			this.lblStepSize.LabelProp = global::Mono.Unix.Catalog.GetString ("Step Size");
			this.vbox2.Add (this.lblStepSize);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblStepSize]));
			w17.Position = 6;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.sclStepSize = new global::Gtk.HScale (null);
			this.sclStepSize.CanFocus = true;
			this.sclStepSize.Name = "sclStepSize";
			this.sclStepSize.Adjustment.Lower = 8;
			this.sclStepSize.Adjustment.Upper = 24;
			this.sclStepSize.Adjustment.PageIncrement = 3;
			this.sclStepSize.Adjustment.StepIncrement = 2;
			this.sclStepSize.Adjustment.Value = 20;
			this.sclStepSize.DrawValue = true;
			this.sclStepSize.Digits = 0;
			this.sclStepSize.ValuePos = ((global::Gtk.PositionType)(2));
			this.vbox2.Add (this.sclStepSize);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.sclStepSize]));
			w18.Position = 7;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lbWT = new global::Gtk.Label ();
			this.lbWT.Name = "lbWT";
			this.lbWT.LabelProp = global::Mono.Unix.Catalog.GetString ("WT");
			this.vbox2.Add (this.lbWT);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lbWT]));
			w19.Position = 8;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.sclWT = new global::Gtk.HScale (null);
			this.sclWT.CanFocus = true;
			this.sclWT.Name = "sclWT";
			this.sclWT.Adjustment.Upper = 10;
			this.sclWT.Adjustment.PageIncrement = 2;
			this.sclWT.Adjustment.StepIncrement = 1;
			this.sclWT.Adjustment.Value = 4;
			this.sclWT.DrawValue = true;
			this.sclWT.Digits = 0;
			this.sclWT.ValuePos = ((global::Gtk.PositionType)(2));
			this.vbox2.Add (this.sclWT);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.sclWT]));
			w20.Position = 9;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.btnBurn = new global::Gtk.Button ();
			this.btnBurn.CanFocus = true;
			this.btnBurn.Name = "btnBurn";
			this.btnBurn.UseUnderline = true;
			this.btnBurn.Label = global::Mono.Unix.Catalog.GetString ("Burn!");
			this.vbox2.Add (this.btnBurn);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.btnBurn]));
			w21.Position = 10;
			w21.Expand = false;
			w21.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w22.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fileImage = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
			this.fileImage.Name = "fileImage";
			this.vbox3.Add (this.fileImage);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fileImage]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.imgPreview = new global::Gtk.Image ();
			this.imgPreview.Name = "imgPreview";
			this.vbox3.Add (this.imgPreview);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.imgPreview]));
			w24.Position = 1;
			w24.Expand = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtLog = new global::Gtk.TextView ();
			this.txtLog.CanFocus = true;
			this.txtLog.Name = "txtLog";
			this.GtkScrolledWindow.Add (this.txtLog);
			this.vbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
			w26.Position = 2;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 723;
			this.DefaultHeight = 442;
			this.Show ();
		}
	}
}
